language: python
env:
  global:
  - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='netcdf4 hdf5 udunits2 coveralls coverage pytest pytest-cov'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=True
  - EVENT_TYPE='push pull_request'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
  - CONDA_CHANNEL_PRIORITY="strict"
  - UNSTABLE_DEPS=False
  - FOO_BAR=cron  # TODO: Replace with TRAVIS_EVENT_TYPE
  - secure: YQ8bTH+9QE78c0wuVAaIdR6KmXbs96iCCYgPgWaN91SLT0zWvGtlGOdWz3XdscxoOInL0V4pbXFDV0h4Al2v6+bFtEW0wr09PQc6HPEFI8Ew+1yCJIXzxxqVUym1Y6TFWoWMAlNV3ZvWkLr+uHW8rl8OUpd3wuVyW8sOWZWd8broq/iNhayOw3oRysC/AfmmGxysqh5+jbWxNUchfiKPHBoIJgD/kWCthmQBdxSz5ohH1WGho2ly6nquNHICRTEtkMxAhVTzpvbTcfNc33AnNcIbPvDK4S+6lZQ8MNYQxX+I8oqOQNHSZzku42oWhtTBrMjL7C+SGcwFhT0gdTp1Ih5bYA9qaIllr5qmobmyxMAxeKRZYcL2bcIErxozj9sqloYJTKknYZiuIDn9mFTt6snHz4h61zR9o/H/ne3O5Oyx1YyhFB0StsHQQML2zy69h9fuaddigp/lKw8j1+Q4gBOFo09Wa/00FGuQhUax9sOuTk+6mIZsho0vLa33lSs1ykTdGt8/C7ohsiZ1zcB3/H4DNawi3UkmKaDRJ0yTlcm6dSj53cJhmhlpaxO9xW8/tSNl132MkfX8MiL5QuCvzuJz/+dgR0u0e3jmBK6uuPxMSnNH4Rr9S9EIW2LAUQ65UeqsMsoFWrC8IysKJX8aSFknl6QdQJM0J4bGuq8V9IM=
jobs:
  include:
  - name: "Python 3.7"
    env: PYTHON_VERSION=3.7
    os: linux
  - name: "Python 3.7 (unstable)"
    env:
      - PYTHON_VERSION=3.7
      - UNSTABLE_DEPS=True
    os: linux
  - name: "Python 3.8"
    env: PYTHON_VERSION=3.8
    os: linux
  allow_failures:
  - name: "Python 3.7 (unstable)"
install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
- if [[ "$UNSTABLE_DEPS" == "True" ]]; then
    pip install
    git+https://github.com/pydata/xarray
    git+https://github.com/pydata/pandas
    git+https://github.com/pytroll/satpy
    git+https://github.com/pytroll/pygac;
  fi
- pip install -e .[tests]
script:
- pytest --cov=pygac_fdr pygac_fdr/tests --ignore=pygac_fdr/tests/test_end2end.py
- if [[ $PYTHON_VERSION == 3.7 && $FOO_BAR == "cron" ]]; then
    python pygac_fdr/tests/test_end2end.py;
  fi
after_success:
- if [[ $PYTHON_VERSION == 3.7 ]]; then coveralls; fi
after_failure:
- if [[ $PYTHON_VERSION == 3.7 && $FOO_BAR == "cron" ]]; then
    curl -u $GITHUB_TOKEN:x-oauth-basic -i -H "Content-Type: application/json" -X POST --data '{"title":"'System tests failed'", "body":"'$TRAVIS_JOB_WEB_URL'"}' https://api.github.com/repos/pytroll/pygac-fdr/issues;
  fi
deploy:
  - provider: pypi
    user: "__token__"
    password:
      secure: EuyAZzfF4YevGjCeXJP/d+jUivIWqEIyWEd7vwfSWX0eJyDfflK+QshdZaXH3cAEUslK7DMJEO8wKJecHnloPRxcPIfdZ5WqSLH7nNCo8MuyuGhk5VCwVi2uoy3ad9AxQxuBsoTCikA3b1A0iHtDTvG6oezQbg+3gyEkbFtyPyTLCLIl8V2QSUw7/Qri3H2M4Nh6JoinS4IyQDEAgsSDL0Wzm/24S1O+5Ibqp8y1au+o8zMviLzH93AVMqh4hrDwHYv5EC9vid0GJy8AVFNQ9/tzISPmkSQXEOiBxvQFf4y+oxtw68TX4ZQ3KTuc7IFK9iXgTapCtZ928LTEasxdhy+M1S6y7/01krsBsuSMHn2druyHAX1FZQPWD5ggCuneFH1ip+lm8ORIrKdYF7WQH7oqKdxCRWQ3wjUy3tEYxVP/QUyclPbX3+dx+CZ4UCVBNiz+NjoFlVLmn4GG2Ubwp7rtwOc7bCJAYiOdoUqOnAx5MzHsQSidLtP63MRCgvM3xM1bgqWj+ZTPwpu9RU8Q6scIOMIN/FyCL/0AnJjKNj1pBwDcAAuSzsWjMfgI/rNKCNP9v/4EbYDdVV0z8XjhLWuZdCbk3wNTPip/vWk77RKxyDSv0x2xIEqIUCmkAGXHYwfRExAq4+ZGyCWmSDd0VLWIfd3HJ2DFNIdzZrjNE90=
    distributions: sdist
    skip_existing: true
    on:
      tags: true
      repo: pytroll/pygac-fdr
